name: PR Housekeeping
on:
  pull_request:
    types: [opened, reopened]
jobs:
  pr_housekeeping:
    name: 'PR Housekeeping'
    runs-on: ubuntu-latest
    steps:
      - uses: ausaccessfed/workflows/.github/actions/pr-housekeeping@main
        with:
          GITHUB_TOKEN: ${{ secrets.ANSIBLE_REPO_SCOPED_TOKEN }}
